### ISSUE TITLE
Want to discuss "Color generator for situations...."

### ISSUE THREAD

**Issue by ahmadfaizan965** [meesha7/daylio-parser#3]
i saw this in your TODO list in README.md. I wanted to know more about this. Do you want to add colors to terminal texts while running your python script ??

**Comment by meesha7** [comment]
The idea is to extend `config.py`, basically right now we have `DEFAULT_MOODS` with mood name and mood color. If a user of the library wants to create a `MoodConfig` instance from a list of moods, they need to specify color for each of them.

Let's say a user has 20 moods and manually entering all the colors can be tiresome, so we would provide some `ColorGenerator` class that would take a list of mood names and assign colors to them, returning `List[Tuple[str, str]]` for the `MoodConfig` constructor. I'd imagine something like [Seabor's color palettes](https://seaborn.pydata.org/tutorial/color_palettes.html).
